server.port=8087
spring.application.name=catalogserviceweb

spring.datasource.url=jdbc:mysql://localhost:3306/minz_catalogweb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

cors.allowed.origins=http://localhost:5173
